# Generated by Django 4.2.19 on 2025-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='content',
            field=models.TextField(),
        ),
    ]
