# Generated by Django 4.2.19 on 2025-02-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_cvanalysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvanalysis',
            old_name='original_text',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='cvanalysis',
            old_name='summary_prompt',
            new_name='text',
        ),
    ]
