# Generated by Django 4.2.19 on 2025-02-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_calendarsubscription_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
